version: "3.8"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dspesquisa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      PGDATA: /var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgresql:pgsql-server"

volumes:
  postgres-data:
  pgadmin-data:
